# Generated by Django 4.1.3 on 2022-11-08 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0003_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('date_release', models.DateField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='entities.entity')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
