# Generated by Django 4.1.3 on 2022-11-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
