# Generated by Django 4.1.3 on 2022-11-08 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Factory', 'Factory'), ('Distributor', 'Distributor'), ('Dealership', 'Dealership'), ('Retail network', 'Retail network'), ('Entrepreneur', 'Entrepreneur')], default='Entrepreneur', max_length=14)),
                ('name', models.CharField(blank=True, default='', max_length=256, null=True, unique=True)),
                ('debt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('model', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('date_release', models.DateField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='entities.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=256, null=True, unique=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='entities.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=56, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=85, null=True)),
                ('street', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('house', models.PositiveIntegerField(blank=True, default='1', null=True)),
                ('contacts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='entities.contacts')),
            ],
        ),
    ]
