# Generated by Django 4.1.3 on 2022-11-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
